config/routes.rb
CRMVer10::Application.routes.draw do
  resources :accounts

  resources :contacts

  root :to => "home#index"

  devise_for :users

  resources :accounts

end

app/models/account.rb
class Account < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  validates_presence_of :name
  validates_uniqueness_of :name, :email, :case_sensitive => false
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name,:email, :password, :password_confirmation, :remember_me
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :authenticate_user!
  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
    @account = Account.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.json
  def new
    @account = Account.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(params[:account])

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render json: @account, status: :created, location: @account }
      else
        format.html { render action: "new" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.json
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_filter :authenticate_user!
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contacts }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = Contact.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render json: @contact, status: :created, location: @contact }
      else
        format.html { render action: "new" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/accounts/_form.html.haml
= form_for @account do |f|
  -if @account.errors.any?
    #error_explanation
      %h2= "#{pluralize(@account.errors.count, "error")} prohibited this account from being saved:"
      %ul
        - @account.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :phone_no
    = f.number_field :phone_no
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :country
    = f.text_field :country
  .field
    = f.label :zipcode
    = f.text_field :zipcode
  .actions
    = f.submit 'Save'

app/views/accounts/edit.html.haml
%h1 Editing account

= render 'form'

= link_to 'Show', @account
\|
= link_to 'Back', accounts_path

app/views/accounts/index.html.haml
%h1 Listing accounts

%table
  %tr
    %th Name
    %th Phone no
    %th Email
    %th City
    %th Country
    %th Zipcode
    %th
    %th
    %th

  - @accounts.each do |account|
    %tr
      %td= account.name
      %td= account.phone_no
      %td= account.email
      %td= account.city
      %td= account.country
      %td= account.zipcode
      %td= link_to 'Show', account
      %td= link_to 'Edit', edit_account_path(account)
      %td= link_to 'Destroy', account, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Account', new_account_path

app/views/accounts/new.html.haml
%h1 New account

= render 'form'

= link_to 'Back', accounts_path

app/views/accounts/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @account.name
%p
  %b Phone no:
  = @account.phone_no
%p
  %b Email:
  = @account.email
%p
  %b City:
  = @account.city
%p
  %b Country:
  = @account.country
%p
  %b Zipcode:
  = @account.zipcode

= link_to 'Edit', edit_account_path(@account)
\|
= link_to 'Back', accounts_path

app/views/contacts/_form.html.haml
= form_for @contact do |f|
  -if @contact.errors.any?
    #error_explanation
      %h2= "#{pluralize(@contact.errors.count, "error")} prohibited this contact from being saved:"
      %ul
        - @contact.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :salutation
    = f.text_field :salutation
  .field
    = f.label :fname
    = f.text_field :fname
  .field
    = f.label :mname
    = f.text_field :mname
  .field
    = f.label :lname
    = f.text_field :lname
  .field
    = f.label :phone_no
    = f.number_field :phone_no
  .field
    = f.label :email
    = f.text_field :email
  .actions
    = f.submit 'Save'

app/views/contacts/edit.html.haml
%h1 Editing contact

= render 'form'

= link_to 'Show', @contact
\|
= link_to 'Back', contacts_path

app/views/contacts/index.html.haml
%h1 Listing contacts

%table
  %tr
    %th Salutation
    %th Fname
    %th Mname
    %th Lname
    %th Phone no
    %th Email
    %th
    %th
    %th

  - @contacts.each do |contact|
    %tr
      %td= contact.salutation
      %td= contact.fname
      %td= contact.mname
      %td= contact.lname
      %td= contact.phone_no
      %td= contact.email
      %td= link_to 'Show', contact
      %td= link_to 'Edit', edit_contact_path(contact)
      %td= link_to 'Destroy', contact, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Contact', new_contact_path

app/views/contacts/new.html.haml
%h1 New contact

= render 'form'

= link_to 'Back', contacts_path

app/views/contacts/show.html.haml
%p#notice= notice

%p
  %b Salutation:
  = @contact.salutation
%p
  %b Fname:
  = @contact.fname
%p
  %b Mname:
  = @contact.mname
%p
  %b Lname:
  = @contact.lname
%p
  %b Phone no:
  = @contact.phone_no
%p
  %b Email:
  = @contact.email

= link_to 'Edit', edit_contact_path(@contact)
\|
= link_to 'Back', contacts_path

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

app/views/layouts/application.html.haml
!!!
%html
 %head
  %title CRMVer10
  = stylesheet_link_tag "reset", "fluid_grid", "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
 %body
  %div(class="container_16 wrapper")
   %div(class="header grid_16")
    = render 'shared/navigation' 
    .clear
   %hr(class="menu-sep grid_16")
   - if user_signed_in?
    %div(class="menu grid_16")
     %div(class="grid_12 menu-bar")
      %ul
       %li 
        =link_to('Accounts', accounts_path)
       %li 
        =link_to('Contacts', contacts_path)
   - if flash.present?
    %div(class="flash_setup grid_16")
     %div(class="grid_12")
      -flash.each do |name, msg|
       = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)
     .clear
   %div(class="content grid_16")              
    =yield

app/views/shared/_navigation.html.haml
%div(class="login_bar grid_3 prefix_13")
 -if user_signed_in?
  = link_to('Logout', destroy_user_session_path, :method => "delete")
  | 
  = link_to('Edit account', edit_user_registration_path)
 -else
  = link_to('Login', new_user_session_path)  
  | 
  = link_to('Sign up', new_user_registration_path)